# _config.yml for juelz-plebcore
baseurl: "/PlebWaveFrontier"  # This is critical for project sites
url: "https://plebware.github.io"

plugins:
  - jekyll-remote-theme

remote_theme: Plebware/pleb-theme
